Join lines of Python version check.
This improves error message for Python 3.4 and earlier versions.

Before:

    $ python3.4 ttyszfury
      File "ttyszfury", line 18
        async def _():
                ^
    SyntaxError: invalid syntax

After:

    $ python3.4 ttyszfury
      File "ttyszfury", line 18
        async def _(): f'{await "# Python >= 3.7 is required #"}'
                ^
    SyntaxError: invalid syntax